Repository ergebnis/php-cs-fixer-config-template, pull requests merged in 2019-12, with the labels that each got.

#19 Enhancement: Use ergebnis/test-util instead of localheinz/test-util
  composer.json
  composer.lock
  test/AutoReview/SrcCodeTest.php
Labels: enhancement

#20 Enhancement: Synchronize with ergebnis/php-library-template
  .github/workflows/continuous-integration.yml
  Makefile
  composer.json
  composer.lock
  phpstan.neon
Labels: enhancement

#21 Enhancement: Synchronize with ergebnis/php-library-template
  .github/CONTRIBUTING.md
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement

#22 Enhancement: Use ergebnis/phpstan-rules instead of localheinz/phpstan-rules
  composer.json
  composer.lock
  phpstan.neon
Labels: enhancement

#24 Enhancement: Use ergebnis/composer-normalize instead of localheinz/composer-normalize
  composer.json
  composer.lock
Labels: dependency

#23 Enhancement: Update phpstan/phpstan and friends
  composer.json
  composer.lock
  phpstan-baseline.neon
  src/Factory.php
  src/RuleSet.php
  src/RuleSet/AbstractRuleSet.php
  test/Unit/FactoryTest.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: dependency

#25 Enhancement: Synchronize with ergebnis/php-library-template
  .dependabot/config.yml
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
  Makefile
Labels: enhancement

#26 Fix: Do not bother checking iterable type
  phpstan.neon
  src/Factory.php
  src/RuleSet.php
  src/RuleSet/AbstractRuleSet.php
  test/Unit/FactoryTest.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug

#27 Fix: add missing quote in error message
  src/Factory.php
  test/Unit/FactoryTest.php
Labels: bug
